# Generated by Django 2.0.6 on 2020-12-08 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sandbox', '0002_auplayer_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='auplayer',
            name='e_id',
            field=models.IntegerField(default=0),
        ),
    ]
