# Generated by Django 2.0.6 on 2020-12-08 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sandbox', '0003_auplayer_e_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='augame',
            name='target',
            field=models.IntegerField(default=0),
        ),
    ]
