# Generated by Django 2.0.6 on 2020-12-09 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sandbox', '0004_augame_target'),
    ]

    operations = [
        migrations.AlterField(
            model_name='augame',
            name='code',
            field=models.CharField(default='CODE', max_length=6, unique=True, verbose_name='code'),
        ),
    ]
