# Generated by Django 2.0.6 on 2020-12-10 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sandbox', '0005_auto_20201209_0130'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auplayer',
            name='x',
        ),
        migrations.RemoveField(
            model_name='auplayer',
            name='y',
        ),
        migrations.AddField(
            model_name='auplayer',
            name='seq',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='auplayer',
            name='xs',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='auplayer',
            name='ys',
            field=models.TextField(default=''),
        ),
    ]
